export const CREATE_TASK = 'CREATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const RENAME_TASK = 'RENAME_TASK';
export const GET_TASKS_BEFORE = 'GET_TASKS_BEFORE';

export const CREATE_REMINDER = 'CREATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const UPDATE_REMINDER_NAME = 'UPDATE_REMINDER_NAME';
export const UPDATE_REMINDER_TIME = 'UPDATE_REMINDER_TIME';

export const CREATE_DAILY_PROGRESS = 'CREATE_DAILY_PROGRESS';
export const UPDATE_DAILY_PROGRESS = 'UPDATE_DAILY_PROGRESS';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';